name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python${{ matrix.python-version }}/site-packages
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --cache-dir ~/.cache/pip --no-deps -e .
        pip install --cache-dir ~/.cache/pip --use-pep517 -e ".[dev]"

    - name: Run tests
      run: |
        python -m pytest tests/ -v

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: 'pip'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python3.9/site-packages
        key: ${{ runner.os }}-pip-3.9-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-3.9-

    - name: Install development dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --cache-dir ~/.cache/pip --no-deps -e .
        pip install --cache-dir ~/.cache/pip --use-pep517 -e ".[dev]"

    - name: Run ruff check
      run: ruff check src/ scripts/

    - name: Run ruff format check
      run: ruff format --check src/ scripts/

    - name: Run mypy type checking
      run: mypy src/

    - name: Run interrogate doc coverage
      run: interrogate src/ --fail-under=90
